services:
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
      target: dev
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - 3000:3000
    command: npm run start:dev
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '9876:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: