services:
  backend:
    container_name: ${CONTAINER_NAME_BACKEND}
    build:
      context: ./backend
      target: dev
      dockerfile: Dockerfile
    image: nestjs:1.0
    networks:
      - transcendence
    depends_on:
      - database
    ports:
      - 3000:3000
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    container_name: ${CONTAINER_NAME_FRONTEND}
    build:
      context: ./frontend
      target: dev
      dockerfile: Dockerfile
    image: vuejs:1.0
    networks:
      - transcendence
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules

  database:
    container_name: ${CONTAINER_NAME_DATABASE}
    image: postgres
    restart: always
    env_file:
      - .env
    networks:
      - transcendence
    ports:
      - '9876:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: {}

networks:
  transcendence: